[phases.setup]
nixPkgs = ["python311", "ffmpeg", "gcc", "pkg-config"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip setuptools wheel",
  "PIP_PREFER_BINARY=1 pip install -r requirements.txt"
]
