# nixpacks.toml
phases.setup
nixPkgs = "python311", "ffmpeg"

# Pip bei Build/Install ausf√ºhren (wheel-first)
phases.install
cmds = "pip install -r requirements.txt"

start
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT"
